name: Test Exercises

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Test Exercises
        run: |
          set -o pipefail
          xcodebuild test \
            -project xcodeProject/ObjectiveC.xcodeproj \
            -scheme xobjectivecTest \
            -destination 'platform=macOS' \
            | xcpretty
