name: Test Exercises

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Test Exercises
        run: |
          set -o pipefail
          xcodebuild test \
            -project xcodeProject/ObjectiveC.xcodeproj \
            -scheme xobjectivecTest \
            -destination 'platform=macOS' \
            | xcpretty
